# Generated by Django 6.0.2 on 2026-02-15 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ministries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('also_known_as', models.CharField(blank=True, max_length=255, null=True)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='members/photos/')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=10)),
                ('year_of_birth', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('estate', models.CharField(blank=True, max_length=100, null=True)),
                ('phase', models.CharField(blank=True, max_length=100, null=True)),
                ('plot', models.CharField(blank=True, max_length=100, null=True)),
                ('door', models.CharField(blank=True, max_length=100, null=True)),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOWED', 'Widowed'), ('DIVORCED', 'Divorced')], default='SINGLE', max_length=20)),
                ('spouse_name', models.CharField(blank=True, max_length=255, null=True)),
                ('spouse_workplace', models.CharField(blank=True, max_length=255, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=255, null=True)),
                ('next_of_kin_relation', models.CharField(blank=True, max_length=100, null=True)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_county', models.CharField(blank=True, max_length=100, null=True)),
                ('ward', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('education_level', models.CharField(blank=True, max_length=100, null=True)),
                ('work_place', models.CharField(blank=True, max_length=255, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('saved', models.BooleanField(default=False)),
                ('saved_date', models.DateField(blank=True, null=True)),
                ('saved_where', models.CharField(blank=True, max_length=255, null=True)),
                ('baptized', models.BooleanField(default=False)),
                ('baptized_date', models.DateField(blank=True, null=True)),
                ('previous_church', models.CharField(blank=True, max_length=255, null=True)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('desired_ministry', models.CharField(blank=True, max_length=255, null=True)),
                ('influence_reason', models.TextField(blank=True, help_text='What influenced you to come to this church?', null=True)),
                ('prayer_need', models.TextField(blank=True, null=True)),
                ('main_ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='ministries.ministry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('school_or_work', models.CharField(blank=True, help_text='School / College / University / Place of Work', max_length=255, null=True)),
                ('class_or_course', models.CharField(blank=True, help_text='Class / Course / Type of Work', max_length=255, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='members.member')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
