# Generated by Django 5.2.4 on 2026-02-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_education_course_member_member_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
